index:
    path: /
    controller: TestConsumer\Controller\DefaultController::index
    defaults:
      _format: 'html'

search_query:
    path: /search-query
    controller: TestConsumer\Controller\DefaultController::queryForm
    defaults:
      _format: 'html'

result:
    path: /result
    controller: TestConsumer\Controller\DefaultController::queryResult
    defaults:
      _format: 'html'